-- =============================================================================
-- V10 — SAV : réclamations et retours
-- =============================================================================
-- Correction A4 : le modèle initial rendait le retour PARTIEL impossible.
-- Un retour porte désormais sur des LIGNES, avec des quantités et un état
-- d'article — parce que « il renvoie 3 chemises sur 10, dont 1 abîmée » est
-- le cas normal, pas l'exception.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- RECLAMATION
-- -----------------------------------------------------------------------------
-- C'est aussi la voie de recours du client qui veut annuler une commande déjà
-- payée : il ne peut pas le faire seul (D-12), il réclame et un humain décide.
-- -----------------------------------------------------------------------------
CREATE TABLE reclamation (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero            varchar(30)  NOT NULL UNIQUE,
    client_id         bigint       NOT NULL REFERENCES client (id),
    commande_id       bigint       NOT NULL REFERENCES commande (id),
    responsable_id    bigint       REFERENCES responsable (id),
    motif             varchar(50)  NOT NULL,
    description       text,
    statut            varchar(20)  NOT NULL DEFAULT 'OUVERTE',
    date_creation     timestamptz  NOT NULL DEFAULT now(),
    date_resolution   timestamptz,

    CONSTRAINT reclamation_statut_valide
        CHECK (statut IN ('OUVERTE', 'EN_COURS', 'RESOLUE', 'FERMEE')),
    CONSTRAINT reclamation_resolution_coherente
        CHECK (statut NOT IN ('RESOLUE', 'FERMEE') OR date_resolution IS NOT NULL)
);

CREATE INDEX reclamation_client_idx   ON reclamation (client_id, date_creation DESC);
CREATE INDEX reclamation_commande_idx ON reclamation (commande_id);
CREATE INDEX reclamation_ouverte_idx  ON reclamation (date_creation) WHERE statut IN ('OUVERTE', 'EN_COURS');


-- -----------------------------------------------------------------------------
-- RETOUR
-- -----------------------------------------------------------------------------
CREATE TABLE retour (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero            varchar(30)  NOT NULL UNIQUE,
    commande_id       bigint       NOT NULL REFERENCES commande (id),
    client_id         bigint       NOT NULL REFERENCES client (id),
    reclamation_id    bigint       REFERENCES reclamation (id),
    motif             varchar(50)  NOT NULL,
    statut            varchar(20)  NOT NULL DEFAULT 'DEMANDE',
    date_creation     timestamptz  NOT NULL DEFAULT now(),
    date_reception    timestamptz,

    CONSTRAINT retour_statut_valide CHECK (statut IN (
        'DEMANDE', 'ACCEPTE', 'REFUSE', 'RECEPTIONNE', 'VALIDE', 'CLOTURE')),
    CONSTRAINT retour_reception_coherente
        CHECK (statut NOT IN ('RECEPTIONNE', 'VALIDE', 'CLOTURE') OR date_reception IS NOT NULL)
);

COMMENT ON TABLE retour IS
    'Le remboursement n''est déclenché qu''au statut VALIDE, donc APRÈS contrôle physique des articles.';

CREATE INDEX retour_commande_idx ON retour (commande_id);
CREATE INDEX retour_client_idx   ON retour (client_id, date_creation DESC);


-- -----------------------------------------------------------------------------
-- LIGNE_RETOUR
-- -----------------------------------------------------------------------------
CREATE TABLE ligne_retour (
    id                  bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retour_id           bigint        NOT NULL REFERENCES retour (id) ON DELETE CASCADE,
    ligne_commande_id   bigint        NOT NULL REFERENCES ligne_commande (id),
    quantite            int           NOT NULL,
    etat_article        varchar(20)   NOT NULL,
    montant_rembourse   numeric(15,2) NOT NULL DEFAULT 0,

    CONSTRAINT ligne_retour_quantite_positive CHECK (quantite > 0),
    CONSTRAINT ligne_retour_etat_valide CHECK (etat_article IN ('NEUF', 'ABIME', 'INUTILISABLE')),
    CONSTRAINT ligne_retour_montant_positif CHECK (montant_rembourse >= 0)
);

COMMENT ON COLUMN ligne_retour.etat_article IS
    'Décide du mouvement de stock : NEUF revient en disponible, ABIME et INUTILISABLE vont en endommagé.';

CREATE INDEX ligne_retour_retour_idx  ON ligne_retour (retour_id);
CREATE INDEX ligne_retour_ligne_cmd_idx ON ligne_retour (ligne_commande_id);


-- -----------------------------------------------------------------------------
-- I-40 — On ne peut pas retourner plus qu'on n'a acheté
-- -----------------------------------------------------------------------------
-- Même raison que I-35 : un agrégat sur plusieurs lignes est hors de portée
-- d'un CHECK. Et ici l'erreur coûte de l'argent — un remboursement de trois
-- articles pour un seul acheté.
--
-- Le cumul porte sur TOUS les retours de la ligne, pas seulement celui-ci :
-- un client peut retourner 2 articles en mars et 2 en avril sur les 3 achetés.
-- -----------------------------------------------------------------------------
CREATE FUNCTION verifier_quantite_retour() RETURNS trigger AS $$
DECLARE
    qte_commandee int;
    qte_deja      int;
BEGIN
    SELECT quantite INTO qte_commandee
      FROM ligne_commande WHERE id = NEW.ligne_commande_id;

    SELECT COALESCE(SUM(lr.quantite), 0) INTO qte_deja
      FROM ligne_retour lr
      JOIN retour r ON r.id = lr.retour_id
     WHERE lr.ligne_commande_id = NEW.ligne_commande_id
       AND lr.id IS DISTINCT FROM NEW.id
       AND r.statut <> 'REFUSE';

    IF qte_deja + NEW.quantite > qte_commandee THEN
        RAISE EXCEPTION
            'I-40 : cumul retourne (%) superieur a la quantite commandee (%) pour la ligne_commande %',
            qte_deja + NEW.quantite, qte_commandee, NEW.ligne_commande_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ligne_retour_quantite_trigger
    BEFORE INSERT OR UPDATE ON ligne_retour
    FOR EACH ROW EXECUTE FUNCTION verifier_quantite_retour();
