-- =============================================================================
-- V11 — Finance marchand : commissions, grand livre, règlements
-- =============================================================================
-- Correction A3, la plus importante du chapitre 02 :
--
--     ON NE STOCKE JAMAIS UN SOLDE COMME SOURCE DE VÉRITÉ.
--     On stocke des ÉCRITURES, et le solde est leur SOMME.
--
-- La table dette_marchand de la spec initiale a donc DISPARU. Un solde stocké
-- ment dès qu'une écriture est ratée — et plus personne ne peut prouver la
-- vérité. C'est le principe de la comptabilité en partie double, vieux de
-- 500 ans, jamais battu.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- REGLE_COMMISSION — un TAUX daté, pas un montant
-- -----------------------------------------------------------------------------
-- La règle sert à CALCULER. La ligne de commande sert à PROUVER : le taux
-- appliqué y est figé au moment de la vente.
-- On date la règle parce qu'on doit pouvoir REJOUER un calcul en cas de
-- litige avec un marchand (voir D-10 pour le cas inverse, les frais).
-- -----------------------------------------------------------------------------
CREATE TABLE regle_commission (
    id                     bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marchand_id            bigint       REFERENCES marchand (id),
    categorie_produit_id   bigint       REFERENCES categorie_produit (id),
    taux                   numeric(5,2) NOT NULL,
    priorite               int          NOT NULL DEFAULT 0,
    date_debut             date         NOT NULL DEFAULT CURRENT_DATE,
    date_fin               date,

    CONSTRAINT regle_commission_taux_valide  CHECK (taux >= 0 AND taux <= 100),
    CONSTRAINT regle_commission_dates_coherentes
        CHECK (date_fin IS NULL OR date_fin >= date_debut)
);

COMMENT ON COLUMN regle_commission.marchand_id IS 'NULL = s''applique à tous les marchands.';
COMMENT ON COLUMN regle_commission.categorie_produit_id IS 'NULL = s''applique à toutes les catégories.';
COMMENT ON COLUMN regle_commission.priorite IS 'La règle la plus spécifique gagne. Résolue par le service.';

CREATE INDEX regle_commission_marchand_idx  ON regle_commission (marchand_id);
CREATE INDEX regle_commission_categorie_idx ON regle_commission (categorie_produit_id);


-- -----------------------------------------------------------------------------
-- REGLEMENT_MARCHAND — ce qu'on verse effectivement au partenaire
-- -----------------------------------------------------------------------------
CREATE TABLE reglement_marchand (
    id               bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero           varchar(30)   NOT NULL UNIQUE,
    marchand_id      bigint        NOT NULL REFERENCES marchand (id),
    montant          numeric(15,2) NOT NULL,
    devise           char(3)       NOT NULL DEFAULT 'XAF',
    moyen            varchar(20)   NOT NULL,
    reference        varchar(100),
    statut           varchar(20)   NOT NULL DEFAULT 'PREVU',
    cree_par         bigint        REFERENCES utilisateur (id),
    date_reglement   timestamptz,
    date_creation    timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT reglement_marchand_montant_positif CHECK (montant > 0),
    CONSTRAINT reglement_marchand_moyen_valide
        CHECK (moyen IN ('MTN_MOMO', 'ORANGE_MONEY', 'VIREMENT', 'ESPECES')),
    CONSTRAINT reglement_marchand_statut_valide
        CHECK (statut IN ('PREVU', 'PAYE', 'ANNULE')),
    CONSTRAINT reglement_marchand_paiement_coherent
        CHECK (statut <> 'PAYE' OR date_reglement IS NOT NULL)
);

COMMENT ON COLUMN reglement_marchand.moyen IS
    'ESPECES est admis ici : c''est un versement de l''entreprise au marchand, pas un encaissement client (D-06).';


-- -----------------------------------------------------------------------------
-- ECRITURE_MARCHAND — le grand livre
-- -----------------------------------------------------------------------------
-- Le solde dû à un marchand est TOUJOURS :
--     SELECT SUM(montant) FROM ecriture_marchand WHERE marchand_id = ?
-- Il n'est stocké nulle part, donc il ne peut pas désynchroniser.
-- -----------------------------------------------------------------------------
CREATE TABLE ecriture_marchand (
    id             bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marchand_id    bigint        NOT NULL REFERENCES marchand (id),
    type           varchar(25)   NOT NULL,
    montant        numeric(15,2) NOT NULL,
    devise         char(3)       NOT NULL DEFAULT 'XAF',
    origine_type   varchar(25)   NOT NULL,
    origine_id     bigint        NOT NULL,
    libelle        varchar(250),
    cree_par       bigint        REFERENCES utilisateur (id),
    date_ecriture  timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT ecriture_marchand_type_valide CHECK (type IN (
        'VENTE', 'COMMISSION', 'RETOUR', 'ANNUL_COMMISSION', 'REGLEMENT', 'AJUSTEMENT')),

    CONSTRAINT ecriture_marchand_origine_valide CHECK (origine_type IN (
        'LIGNE_COMMANDE', 'LIGNE_RETOUR', 'REGLEMENT', 'MANUEL')),

    CONSTRAINT ecriture_marchand_montant_non_nul CHECK (montant <> 0),

    -- I-41 : le SIGNE est imposé par le type. Une VENTE ne peut pas être
    -- négative, une COMMISSION ne peut pas être positive. Une inversion de
    -- signe fausserait tous les soldes sans jamais lever d'erreur.
    -- AJUSTEMENT est le seul type libre : c'est la soupape de correction.
    CONSTRAINT ecriture_marchand_signe_coherent CHECK (
        (type = 'VENTE'            AND montant > 0) OR
        (type = 'COMMISSION'       AND montant < 0) OR
        (type = 'RETOUR'           AND montant < 0) OR
        (type = 'ANNUL_COMMISSION' AND montant > 0) OR
        (type = 'REGLEMENT'        AND montant < 0) OR
        (type = 'AJUSTEMENT')
    )
);

COMMENT ON TABLE ecriture_marchand IS
    'IMMUABLE (I-42) : aucun UPDATE ni DELETE. Une erreur se corrige par une écriture inverse, jamais en effaçant.';
COMMENT ON COLUMN ecriture_marchand.montant IS
    'SIGNÉ. Positif = dû au marchand. Négatif = retiré de ce qu''on lui doit.';

CREATE INDEX ecriture_marchand_marchand_idx ON ecriture_marchand (marchand_id, date_ecriture);
CREATE INDEX ecriture_marchand_origine_idx  ON ecriture_marchand (origine_type, origine_id);
