-- =============================================================================
-- V12 — Surveillance, audit et système
-- =============================================================================
-- Trois journaux qui se ressemblent et qu'il ne faut JAMAIS confondre :
--
--   activite_client     ce que fait LE CLIENT        → comprendre son parcours
--   evenement_securite  faits d'AUTHENTIFICATION      → détecter une anomalie
--   audit_log           actions INTERNES sur données  → responsabilité interne
--
-- Sans règle claire, tout finit dans la même table et plus rien n'est
-- exploitable. Un même geste peut légitimement écrire dans deux d'entre elles.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- ACTIVITE_CLIENT
-- -----------------------------------------------------------------------------
CREATE TABLE activite_client (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     bigint      NOT NULL REFERENCES client (id) ON DELETE CASCADE,
    type          varchar(30) NOT NULL,
    appareil_id   bigint      REFERENCES appareil_connu (id),
    adresse_ip    inet,
    contexte      jsonb       NOT NULL DEFAULT '{}'::jsonb,
    date_heure    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT activite_client_type_valide CHECK (type IN (
        'CONNEXION', 'DECONNEXION', 'VUE_PRODUIT', 'AJOUT_PANIER',
        'COMMANDE', 'ANNULATION', 'PAIEMENT', 'RECLAMATION'))
);

CREATE INDEX activite_client_client_idx ON activite_client (client_id, date_heure DESC);
CREATE INDEX activite_client_type_idx   ON activite_client (type, date_heure DESC);


-- -----------------------------------------------------------------------------
-- EVENEMENT_SECURITE
-- -----------------------------------------------------------------------------
-- Porté par utilisateur et non par client : un responsable aussi peut se faire
-- attaquer, et c'est même plus grave.
-- -----------------------------------------------------------------------------
CREATE TABLE evenement_securite (
    id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id   bigint      REFERENCES utilisateur (id) ON DELETE SET NULL,
    type             varchar(40) NOT NULL,
    gravite          varchar(20) NOT NULL DEFAULT 'INFO',
    appareil_id      bigint      REFERENCES appareil_connu (id),
    adresse_ip       inet,
    description      text,
    date_heure       timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT evenement_securite_type_valide CHECK (type IN (
        'CONNEXION_REUSSIE', 'ECHEC_CONNEXION', 'NOUVEL_APPAREIL',
        'CHANGEMENT_MOT_DE_PASSE', 'CHANGEMENT_EMAIL', 'CHANGEMENT_TELEPHONE',
        'ECHEC_PAIEMENT', 'ACTIVITE_INHABITUELLE', 'BLOCAGE_COMPTE')),
    CONSTRAINT evenement_securite_gravite_valide
        CHECK (gravite IN ('INFO', 'FAIBLE', 'MOYENNE', 'HAUTE', 'CRITIQUE'))
);

COMMENT ON COLUMN evenement_securite.utilisateur_id IS
    'ON DELETE SET NULL : l''événement survit à la suppression du compte. Un journal effaçable n''est pas un journal.';

CREATE INDEX evenement_securite_utilisateur_idx ON evenement_securite (utilisateur_id, date_heure DESC);
CREATE INDEX evenement_securite_type_idx        ON evenement_securite (type, date_heure DESC);


-- -----------------------------------------------------------------------------
-- SCORE_RISQUE_CLIENT — et son explication (correction A14)
-- -----------------------------------------------------------------------------
-- La spec exigeait « le score doit être explicable » mais ne stockait qu'un
-- nombre. Un écran d'administration n'affiche pas « 78 » : il affiche les
-- quatre phrases qui expliquent le 78.
-- -----------------------------------------------------------------------------
CREATE TABLE score_risque_client (
    id                   bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id            bigint       NOT NULL REFERENCES client (id) ON DELETE CASCADE,
    score                numeric(5,2) NOT NULL,
    niveau               varchar(10)  NOT NULL,
    version_algorithme   varchar(20)  NOT NULL,
    details              jsonb        NOT NULL DEFAULT '{}'::jsonb,
    date_calcul          timestamptz  NOT NULL DEFAULT now(),

    -- I-45
    CONSTRAINT score_risque_borne CHECK (score >= 0 AND score <= 100),
    CONSTRAINT score_risque_niveau_valide CHECK (niveau IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    -- Le niveau ne peut pas contredire le score.
    CONSTRAINT score_risque_niveau_coherent CHECK (
        (niveau = 'LOW'      AND score <  25) OR
        (niveau = 'MEDIUM'   AND score >= 25 AND score < 50) OR
        (niveau = 'HIGH'     AND score >= 50 AND score < 80) OR
        (niveau = 'CRITICAL' AND score >= 80)
    )
);

COMMENT ON COLUMN score_risque_client.version_algorithme IS
    'Indispensable : un 78 calculé en v1.0 et un 78 en v1.2 ne veulent pas dire la même chose.';
COMMENT ON COLUMN score_risque_client.details IS
    'Les signaux et leurs poids. C''est ce qui est affiché à l''Admin, pas le nombre.';

CREATE INDEX score_risque_client_idx ON score_risque_client (client_id, date_calcul DESC);


-- -----------------------------------------------------------------------------
-- ALERTE_SECURITE — l'humain décide, jamais le système (règle fondatrice n°2)
-- -----------------------------------------------------------------------------
CREATE TABLE alerte_securite (
    id                      bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id               bigint      NOT NULL REFERENCES client (id) ON DELETE CASCADE,
    evenement_securite_id   bigint      REFERENCES evenement_securite (id),
    type                    varchar(40) NOT NULL,
    gravite                 varchar(20) NOT NULL,
    statut                  varchar(20) NOT NULL DEFAULT 'OUVERTE',
    traite_par              bigint      REFERENCES utilisateur (id),
    decision                text,
    date_creation           timestamptz NOT NULL DEFAULT now(),
    date_traitement         timestamptz,

    CONSTRAINT alerte_securite_gravite_valide CHECK (gravite IN ('FAIBLE', 'MOYENNE', 'HAUTE', 'CRITIQUE')),
    CONSTRAINT alerte_securite_statut_valide  CHECK (statut IN ('OUVERTE', 'EN_COURS', 'TRAITEE', 'IGNOREE')),
    CONSTRAINT alerte_securite_traitement_coherent
        CHECK (statut NOT IN ('TRAITEE', 'IGNOREE') OR (traite_par IS NOT NULL AND date_traitement IS NOT NULL))
);

COMMENT ON COLUMN alerte_securite.decision IS
    'Ce que l''humain a décidé, et pourquoi. Un score HIGH ne bloque jamais personne automatiquement.';

CREATE INDEX alerte_securite_ouverte_idx ON alerte_securite (gravite, date_creation DESC)
    WHERE statut IN ('OUVERTE', 'EN_COURS');


-- -----------------------------------------------------------------------------
-- AUDIT_LOG — qui a modifié quoi, et qu'est-ce que ça valait avant
-- -----------------------------------------------------------------------------
CREATE TABLE audit_log (
    id                 bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id     bigint      REFERENCES utilisateur (id) ON DELETE SET NULL,
    acteur_nom         varchar(200) NOT NULL,
    acteur_email       varchar(255),
    action             varchar(60) NOT NULL,
    entite             varchar(60) NOT NULL,
    entite_id          bigint,
    ancienne_valeur    jsonb,
    nouvelle_valeur    jsonb,
    adresse_ip         inet,
    date_heure         timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE audit_log IS
    'IMMUABLE (I-44). ON DELETE SET NULL sur l''acteur, JAMAIS CASCADE : un audit qu''on efface en supprimant un utilisateur n''est pas un audit.';
COMMENT ON COLUMN audit_log.acteur_nom IS
    'COPIE du nom au moment de l''action. Survit à la suppression du compte.';
COMMENT ON COLUMN audit_log.ancienne_valeur IS
    'jsonb et non text : on veut pouvoir demander « qui a changé le prix », pas relire du texte.';

CREATE INDEX audit_log_entite_idx      ON audit_log (entite, entite_id, date_heure DESC);
CREATE INDEX audit_log_utilisateur_idx ON audit_log (utilisateur_id, date_heure DESC);
CREATE INDEX audit_log_date_idx        ON audit_log (date_heure DESC);


-- -----------------------------------------------------------------------------
-- NOTIFICATION
-- -----------------------------------------------------------------------------
CREATE TABLE notification (
    id               bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id   bigint       NOT NULL REFERENCES utilisateur (id) ON DELETE CASCADE,
    type             varchar(40)  NOT NULL,
    titre            varchar(200) NOT NULL,
    contenu          text,
    lue              boolean      NOT NULL DEFAULT false,
    date_creation    timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX notification_non_lues_idx ON notification (utilisateur_id, date_creation DESC) WHERE NOT lue;


-- -----------------------------------------------------------------------------
-- PIECE_JOINTE — générique (correction A17)
-- -----------------------------------------------------------------------------
-- La spec parlait de « preuves » sans jamais prévoir de table. Un message, une
-- réclamation, un incident, un contrôle qualité ont tous besoin de photos.
--
-- Référence POLYMORPHE (proprietaire_type + proprietaire_id) : pas de clé
-- étrangère possible, c'est le prix à payer. Acceptable ici parce qu'une pièce
-- jointe orpheline n'a aucune conséquence métier — contrairement à une
-- écriture comptable orpheline.
-- -----------------------------------------------------------------------------
CREATE TABLE piece_jointe (
    id                 bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proprietaire_type  varchar(30)  NOT NULL,
    proprietaire_id    bigint       NOT NULL,
    nom_fichier        varchar(255) NOT NULL,
    cle_objet          varchar(500) NOT NULL,
    type_mime          varchar(100),
    taille_octets      bigint,
    televerse_par      bigint       REFERENCES utilisateur (id),
    date_creation      timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT piece_jointe_proprietaire_valide CHECK (proprietaire_type IN (
        'MESSAGE', 'RECLAMATION', 'RETOUR', 'INCIDENT', 'EVENEMENT_EXPEDITION', 'PAIEMENT')),
    CONSTRAINT piece_jointe_taille_positive
        CHECK (taille_octets IS NULL OR taille_octets > 0)
);

CREATE INDEX piece_jointe_proprietaire_idx ON piece_jointe (proprietaire_type, proprietaire_id);
