-- =============================================================================
-- V13 — Mesure : vues, favoris, agrégats
-- =============================================================================
-- Ce domaine était TOTALEMENT absent de la spécification (correction A2), alors
-- que sa §20 réclamait « vues, favoris, paniers, produits tendance ».
--
-- Pourquoi c'était bloquant et pas « à faire plus tard » :
--     une vue non enregistrée est DÉFINITIVEMENT perdue.
-- Un écran peut se coder après. Une donnée non collectée ne se rattrape jamais.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- VUE_PRODUIT — l'écriture détaillée
-- -----------------------------------------------------------------------------
-- Table à forte volumétrie : purgée au bout de 90 jours (D-15), après
-- agrégation. On perd « qui a vu quoi à quelle heure » au-delà de 3 mois,
-- on garde les statistiques pour toujours.
-- -----------------------------------------------------------------------------
CREATE TABLE vue_produit (
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produit_id   bigint      NOT NULL REFERENCES produit (id) ON DELETE CASCADE,
    client_id    bigint      REFERENCES client (id) ON DELETE SET NULL,
    session_id   varchar(64),
    source       varchar(20),
    adresse_ip   inet,
    date_heure   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT vue_produit_source_valide CHECK (source IS NULL OR source IN (
        'RECHERCHE', 'CATEGORIE', 'LIEN_DIRECT', 'SUGGESTION', 'FAVORIS'))
);

COMMENT ON COLUMN vue_produit.client_id IS
    'NULL pour un visiteur non connecté : la vitrine est publique, même si commander exige un compte (D-07).';

CREATE INDEX vue_produit_produit_date_idx ON vue_produit (produit_id, date_heure);
CREATE INDEX vue_produit_purge_idx        ON vue_produit (date_heure);


-- -----------------------------------------------------------------------------
-- FAVORI
-- -----------------------------------------------------------------------------
CREATE TABLE favori (
    client_id    bigint      NOT NULL REFERENCES client (id) ON DELETE CASCADE,
    produit_id   bigint      NOT NULL REFERENCES produit (id) ON DELETE CASCADE,
    date_ajout   timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (client_id, produit_id)
);

CREATE INDEX favori_produit_idx ON favori (produit_id);


-- -----------------------------------------------------------------------------
-- STATISTIQUE_PRODUIT_JOUR — la lecture agrégée
-- -----------------------------------------------------------------------------
-- Une ligne par produit et par jour. Compter les vues d'un produit sur 30 jours
-- en scannant vue_produit devient lent dès quelques millions de lignes ; ici
-- on lit 30 lignes.
--
-- C'est le principe ÉCRITURE DÉTAILLÉE / LECTURE AGRÉGÉE.
-- -----------------------------------------------------------------------------
CREATE TABLE statistique_produit_jour (
    produit_id          bigint        NOT NULL REFERENCES produit (id) ON DELETE CASCADE,
    jour                date          NOT NULL,
    vues                int           NOT NULL DEFAULT 0,
    vues_uniques        int           NOT NULL DEFAULT 0,
    ajouts_panier       int           NOT NULL DEFAULT 0,
    commandes           int           NOT NULL DEFAULT 0,
    quantite_vendue     int           NOT NULL DEFAULT 0,
    chiffre_affaires    numeric(15,2) NOT NULL DEFAULT 0,
    retours             int           NOT NULL DEFAULT 0,

    PRIMARY KEY (produit_id, jour),

    CONSTRAINT statistique_produit_jour_positifs CHECK (
        vues >= 0 AND vues_uniques >= 0 AND ajouts_panier >= 0
        AND commandes >= 0 AND quantite_vendue >= 0
        AND chiffre_affaires >= 0 AND retours >= 0),

    CONSTRAINT statistique_produit_jour_uniques_coherentes
        CHECK (vues_uniques <= vues)
);

COMMENT ON TABLE statistique_produit_jour IS
    'Recalculée chaque nuit depuis vue_produit, ligne_commande et ligne_retour. Conservée indéfiniment : une ligne par produit et par jour, c''est minuscule.';

CREATE INDEX statistique_produit_jour_idx ON statistique_produit_jour (jour DESC);
