-- =============================================================================
-- V2 — IAM : utilisateurs, responsables, catégories et permissions
-- =============================================================================
-- Le domaine le plus structurant du SI : c'est lui qui décide qui a le droit
-- de faire quoi. Voir chapitre 01 §4 et chapitre 03 §4.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- UTILISATEUR — la racine de toute identité
-- -----------------------------------------------------------------------------
-- Stratégie d'héritage JOINED : CLIENT et RESPONSABLE sont des tables filles
-- qui partagent la clé primaire. ADMIN et SUPER_ADMIN n'ont pas d'attribut
-- propre : la colonne `type` suffit à les distinguer (correction A1).
-- -----------------------------------------------------------------------------
CREATE TABLE utilisateur (
    id                       bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                     varchar(20)  NOT NULL,
    nom                      varchar(100) NOT NULL,
    prenom                   varchar(100),
    email                    varchar(255) NOT NULL,
    telephone                varchar(30),
    mot_de_passe             varchar(255) NOT NULL,
    statut                   varchar(20)  NOT NULL DEFAULT 'ACTIF',
    deux_facteurs_actif      boolean      NOT NULL DEFAULT false,
    langue                   char(2)      NOT NULL DEFAULT 'fr' REFERENCES langue (code),
    date_creation            timestamptz  NOT NULL DEFAULT now(),
    date_modification        timestamptz,
    date_derniere_connexion  timestamptz,

    CONSTRAINT utilisateur_type_valide
        CHECK (type IN ('SUPER_ADMIN', 'ADMIN', 'RESPONSABLE', 'CLIENT')),
    CONSTRAINT utilisateur_statut_valide
        CHECK (statut IN ('ACTIF', 'INACTIF', 'BLOQUE'))
);

COMMENT ON COLUMN utilisateur.langue IS
    'Préférence d''affichage. Portée par utilisateur et non par client, car le back-office est aussi trilingue.';

-- I-01 : un e-mail identifie un seul utilisateur.
-- L'index porte sur lower(email) : "Paul@x.cm" et "paul@x.cm" sont le même compte.
CREATE UNIQUE INDEX utilisateur_email_unique ON utilisateur (lower(email));

CREATE INDEX utilisateur_type_statut_idx ON utilisateur (type, statut);


-- -----------------------------------------------------------------------------
-- CLIENT
-- -----------------------------------------------------------------------------
CREATE TABLE client (
    id                bigint      PRIMARY KEY REFERENCES utilisateur (id),
    code_client       varchar(20) NOT NULL UNIQUE,
    date_inscription  timestamptz NOT NULL DEFAULT now(),
    statut            varchar(20) NOT NULL DEFAULT 'ACTIF',

    CONSTRAINT client_statut_valide CHECK (statut IN ('ACTIF', 'INACTIF', 'BLOQUE'))
);


-- -----------------------------------------------------------------------------
-- RESPONSABLE
-- -----------------------------------------------------------------------------
CREATE TABLE responsable (
    id             bigint      PRIMARY KEY REFERENCES utilisateur (id),
    matricule      varchar(20) NOT NULL UNIQUE,
    date_embauche  date,
    statut         varchar(20) NOT NULL DEFAULT 'ACTIF',

    CONSTRAINT responsable_statut_valide CHECK (statut IN ('ACTIF', 'INACTIF'))
);


-- -----------------------------------------------------------------------------
-- CATEGORIE_RESPONSABLE — le profil métier, qui sert aussi de titre affiché
-- -----------------------------------------------------------------------------
CREATE TABLE categorie_responsable (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom          varchar(100) NOT NULL UNIQUE,
    description  text,
    statut       varchar(20)  NOT NULL DEFAULT 'ACTIF',

    CONSTRAINT categorie_responsable_statut_valide CHECK (statut IN ('ACTIF', 'INACTIF'))
);

COMMENT ON COLUMN categorie_responsable.nom IS
    'Sert de titre affiché du responsable. Il n''existe pas de champ titre redondant.';


-- -----------------------------------------------------------------------------
-- RESPONSABLE_CATEGORIE — un responsable peut cumuler plusieurs profils (D-02)
-- -----------------------------------------------------------------------------
CREATE TABLE responsable_categorie (
    responsable_id     bigint      NOT NULL REFERENCES responsable (id) ON DELETE CASCADE,
    categorie_id       bigint      NOT NULL REFERENCES categorie_responsable (id),
    principale         boolean     NOT NULL DEFAULT false,
    date_affectation   timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (responsable_id, categorie_id)
);

-- I-02 : exactement une catégorie principale par responsable.
-- Encore un index unique partiel : il n'interdit que le SECOND "true".
-- (Le "au moins une" ne peut pas être exprimé en SQL — il vit dans le service.)
CREATE UNIQUE INDEX responsable_categorie_principale_unique
    ON responsable_categorie (responsable_id) WHERE principale;


-- -----------------------------------------------------------------------------
-- CAS_UTILISATION — le catalogue des fonctionnalités RÉELLEMENT implémentées
-- -----------------------------------------------------------------------------
-- Un Admin ne peut jamais inventer une permission : il choisit dans cette
-- table, alimentée par le SuperAdmin et par les migrations.
-- -----------------------------------------------------------------------------
CREATE TABLE cas_utilisation (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         varchar(60)  NOT NULL UNIQUE,
    nom          varchar(150) NOT NULL,
    description  text,
    module       varchar(50)  NOT NULL,
    statut       varchar(20)  NOT NULL DEFAULT 'ACTIF',

    CONSTRAINT cas_utilisation_statut_valide CHECK (statut IN ('ACTIF', 'INACTIF')),
    -- Le code est technique : majuscules, chiffres et underscores uniquement.
    CONSTRAINT cas_utilisation_code_format CHECK (code ~ '^[A-Z][A-Z0-9_]*$')
);

COMMENT ON COLUMN cas_utilisation.code IS
    'Immuable. Utilisé par le code Java ET comme clé de traduction dans les fichiers i18n (D-09).';

CREATE INDEX cas_utilisation_module_idx ON cas_utilisation (module);


-- -----------------------------------------------------------------------------
-- CATEGORIE_CAS_UTILISATION — les permissions accordées par un profil
-- -----------------------------------------------------------------------------
CREATE TABLE categorie_cas_utilisation (
    categorie_id        bigint NOT NULL REFERENCES categorie_responsable (id) ON DELETE CASCADE,
    cas_utilisation_id  bigint NOT NULL REFERENCES cas_utilisation (id) ON DELETE CASCADE,

    PRIMARY KEY (categorie_id, cas_utilisation_id)
);


-- -----------------------------------------------------------------------------
-- RESPONSABLE_CAS_UTILISATION — les exceptions individuelles
-- -----------------------------------------------------------------------------
-- La clé primaire composite garantit I-04 : une permission ne peut pas être
-- à la fois ajoutée et retirée pour le même responsable.
-- -----------------------------------------------------------------------------
CREATE TABLE responsable_cas_utilisation (
    responsable_id      bigint      NOT NULL REFERENCES responsable (id) ON DELETE CASCADE,
    cas_utilisation_id  bigint      NOT NULL REFERENCES cas_utilisation (id) ON DELETE CASCADE,
    type                varchar(10) NOT NULL,
    motif               text,
    accorde_par         bigint      REFERENCES utilisateur (id),
    date_creation       timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (responsable_id, cas_utilisation_id),
    CONSTRAINT responsable_cas_utilisation_type_valide CHECK (type IN ('ADD', 'REMOVE'))
);

COMMENT ON TABLE responsable_cas_utilisation IS
    'Exceptions individuelles. Le REMOVE s''applique APRÈS l''union de toutes les catégories (D-02).';


-- -----------------------------------------------------------------------------
-- APPAREIL_CONNU — pour détecter un « nouvel appareil » (§18 de la spec)
-- -----------------------------------------------------------------------------
CREATE TABLE appareil_connu (
    id                      bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id          bigint       NOT NULL REFERENCES utilisateur (id) ON DELETE CASCADE,
    empreinte               varchar(128) NOT NULL,
    libelle                 varchar(150),
    de_confiance            boolean      NOT NULL DEFAULT false,
    premiere_utilisation    timestamptz  NOT NULL DEFAULT now(),
    derniere_utilisation    timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT appareil_connu_unique UNIQUE (utilisateur_id, empreinte)
);
