-- =============================================================================
-- V30 — La messagerie interne à l'équipe
-- =============================================================================
-- 🎯 CE N'EST PAS LA MÊME CHOSE QU'UNE CONVERSATION CLIENT.
--
--    `conversation` (V8) relie UN CLIENT à UN RESPONSABLE, passe par une file
--    d'attente, s'affecte, se ferme, et se note. Rien de tout cela n'a de sens
--    entre deux collègues : on ne prend pas en charge un collègue, on ne le
--    clôt pas, et on ne l'évalue pas.
--
--    Réutiliser la même table aurait demandé de rendre `client_id` facultatif
--    et de neutraliser la moitié des contraintes — c'est-à-dire de perdre
--    exactement ce qui protège les conversations client.
--
-- Deux tables, donc. Elles se ressemblent : c'est normal, elles décrivent deux
-- choses qui se ressemblent et qui ne sont pas la même.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- FIL INTERNE
-- -----------------------------------------------------------------------------
-- Un fil relie DEUX responsables. Pas plus.
--
-- ⚠️ La paire est ORDONNÉE par identifiant croissant, et un index unique le
--    fait respecter. Sans cela, A→B et B→A donneraient deux fils pour la même
--    discussion : chacun verrait la moitié des messages et croirait l'autre
--    muet.
-- -----------------------------------------------------------------------------
CREATE TABLE fil_interne (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Toujours le plus petit identifiant des deux.
    responsable_a  bigint      NOT NULL REFERENCES responsable (id) ON DELETE CASCADE,
    responsable_b  bigint      NOT NULL REFERENCES responsable (id) ON DELETE CASCADE,

    date_creation  timestamptz NOT NULL DEFAULT now(),
    date_dernier   timestamptz NOT NULL DEFAULT now(),

    -- On ne s'écrit pas à soi-même : le fil n'aurait aucun second lecteur.
    CONSTRAINT fil_deux_personnes CHECK (responsable_a <> responsable_b),

    -- L'ordre est une INVARIANTE, pas une convention d'écriture : la faire
    -- respecter par la base évite qu'un appel oublié la casse un jour.
    CONSTRAINT fil_paire_ordonnee CHECK (responsable_a < responsable_b)
);

CREATE UNIQUE INDEX fil_interne_paire_unique
    ON fil_interne (responsable_a, responsable_b);

-- « Mes fils, le plus récent d'abord » est la seule question posée à cette
-- table. Deux index, parce qu'on peut être d'un côté comme de l'autre.
CREATE INDEX fil_interne_a_idx ON fil_interne (responsable_a, date_dernier DESC);
CREATE INDEX fil_interne_b_idx ON fil_interne (responsable_b, date_dernier DESC);


-- -----------------------------------------------------------------------------
-- MESSAGE INTERNE
-- -----------------------------------------------------------------------------
CREATE TABLE message_interne (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fil_id        bigint      NOT NULL REFERENCES fil_interne (id) ON DELETE CASCADE,
    expediteur_id bigint      NOT NULL REFERENCES responsable (id),

    contenu       text        NOT NULL,

    -- ⚠️ La date de LECTURE, et non un booléen « lu ».
    --
    --    « Quand ? » se pose toujours après « est-ce lu ? », et un booléen ne
    --    sait pas y répondre. La question se pose exactement le jour où
    --    quelqu'un affirme n'avoir jamais reçu la consigne.
    date_lecture  timestamptz,

    date_envoi    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT message_interne_non_vide CHECK (length(trim(contenu)) > 0)
);

CREATE INDEX message_interne_fil_idx ON message_interne (fil_id, date_envoi);

-- « Combien de messages non lus ? » s'affiche sur CHAQUE écran du back-office.
-- Un index partiel : les messages lus sont l'écrasante majorité et n'ont rien
-- à faire dans celui-ci.
CREATE INDEX message_interne_non_lus_idx
    ON message_interne (fil_id, expediteur_id)
    WHERE date_lecture IS NULL;


-- -----------------------------------------------------------------------------
-- BLOCAGE
-- -----------------------------------------------------------------------------
-- 🎯 « Un supérieur peut vous bloquer pour que vous ne puissiez plus lui
--    écrire. »
--
-- ⚠️ LE BLOCAGE EST UNILATÉRAL ET ORIENTÉ, et c'est tout le sujet.
--
--    `bloqueur` cesse de recevoir des messages de `bloque`. L'inverse reste
--    vrai : un directeur qui bloque un magasinier peut toujours lui écrire.
--    C'est délibéré — le contraire ferait du blocage une rupture de la chaîne
--    de commandement, alors que ce qu'on veut est seulement se protéger d'une
--    sollicitation.
--
-- ⚠️ Il n'y a PAS de hiérarchie dans ce schéma, et on n'en invente pas une
--    ici. Qui a le droit de bloquer est décidé par la permission
--    MESSAGE_INTERNE_BLOQUER, accordée aux catégories de responsables qu'on
--    juge « supérieures ». C'est le même mécanisme que partout ailleurs, et il
--    se règle sans migration.
-- -----------------------------------------------------------------------------
CREATE TABLE blocage_message (
    bloqueur_id   bigint      NOT NULL REFERENCES responsable (id) ON DELETE CASCADE,
    bloque_id     bigint      NOT NULL REFERENCES responsable (id) ON DELETE CASCADE,

    motif         varchar(300),
    date_blocage  timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (bloqueur_id, bloque_id),

    CONSTRAINT blocage_pas_soi_meme CHECK (bloqueur_id <> bloque_id)
);

-- La question posée à chaque envoi : « celui à qui j'écris m'a-t-il bloqué ? »
CREATE INDEX blocage_bloque_idx ON blocage_message (bloque_id);


-- -----------------------------------------------------------------------------
-- LES PERMISSIONS
-- -----------------------------------------------------------------------------
-- Aucune n'est accordée ici : une migration qui distribue des droits les
-- redonnerait à chaque environnement, y compris ceux où on venait de les
-- retirer. C'est un Admin qui les pose, catégorie par catégorie.
-- -----------------------------------------------------------------------------
INSERT INTO cas_utilisation (code, nom, description, module) VALUES
('MESSAGE_INTERNE_ECRIRE',  'Écrire à un collègue',
 'Ouvrir un fil interne et y envoyer des messages.',                 'MESSAGE_INTERNE'),
('MESSAGE_INTERNE_BLOQUER', 'Bloquer un collègue',
 'Empêcher un collègue de vous écrire. Réservé à l''encadrement.',   'MESSAGE_INTERNE');


COMMENT ON TABLE fil_interne IS
    'Un fil entre DEUX responsables. La paire est ordonnée par identifiant '
    'croissant : sans cela, A vers B et B vers A donneraient deux fils pour la '
    'même discussion, et chacun croirait l''autre muet.';

COMMENT ON TABLE blocage_message IS
    'Blocage UNILATÉRAL et ORIENTÉ : le bloqueur cesse de recevoir des messages '
    'du bloqué, mais peut toujours lui écrire. Le contraire ferait du blocage '
    'une rupture de la chaîne de commandement.';
