-- =============================================================================
-- V38 — Se connecter avec Google, Facebook ou TikTok
-- =============================================================================
-- Deux changements, et le premier est le plus delicat : on RELACHE une
-- contrainte qui tenait depuis V2.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Un compte peut n avoir AUCUN mot de passe
-- -----------------------------------------------------------------------------
-- Quelqu un qui entre par « Continuer avec Google » n en choisit jamais. Lui en
-- fabriquer un au hasard serait pire que de l autoriser a ne pas en avoir :
-- personne ne le connaitrait, il ne pourrait jamais servir, et il donnerait
-- l illusion que le compte est protege par un secret.
ALTER TABLE utilisateur
    ALTER COLUMN mot_de_passe DROP NOT NULL;


-- -----------------------------------------------------------------------------
-- 2. Les identites chez les fournisseurs
-- -----------------------------------------------------------------------------
CREATE TABLE identite_sociale (
    id             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    utilisateur_id bigint       NOT NULL REFERENCES utilisateur (id) ON DELETE CASCADE,

    fournisseur    varchar(20)  NOT NULL,

    -- L identifiant STABLE chez le fournisseur : le « sub » de Google.
    --
    -- ⚠️ C est LUI la cle d identite, jamais l adresse e-mail.
    --    Une adresse change, et peut etre reattribuee a quelqu un d autre.
    --    Le sub, lui, designe la meme personne a vie.
    sujet          varchar(255) NOT NULL,

    -- L adresse telle que le fournisseur l annoncait CE JOUR-LA.
    --
    -- Conservee pour le diagnostic — « pourquoi ce compte a-t-il ete
    -- rattache ? » — et jamais relue pour identifier. C est la regle de la
    -- photographie du chapitre 03 appliquee a une donnee technique.
    email_annonce  varchar(255),

    date_creation      timestamptz NOT NULL DEFAULT now(),
    date_derniere_utilisation timestamptz,

    CONSTRAINT identite_sociale_fournisseur_valide
        CHECK (fournisseur IN ('GOOGLE', 'FACEBOOK', 'TIKTOK'))
);

-- Deux personnes ne peuvent pas partager la meme identite chez un fournisseur.
-- C est la contrainte qui empeche le vol de compte par collision de sujet.
CREATE UNIQUE INDEX identite_sociale_unique
    ON identite_sociale (fournisseur, sujet);

-- Un utilisateur ne rattache qu UNE fois chaque fournisseur.
--
-- Sans cet index, cliquer deux fois sur « Continuer avec Google » creerait
-- deux lignes identiques — invisible, jusqu au jour ou on compte les comptes.
CREATE UNIQUE INDEX identite_sociale_par_utilisateur
    ON identite_sociale (utilisateur_id, fournisseur);

CREATE INDEX identite_sociale_utilisateur_idx
    ON identite_sociale (utilisateur_id);

COMMENT ON COLUMN identite_sociale.sujet IS
    'Identifiant stable chez le fournisseur (sub OIDC). C''est la cle d''identite, jamais l''e-mail.';


-- -----------------------------------------------------------------------------
-- 3. Un compte a un mot de passe OU une identite sociale, jamais ni l un ni l autre
-- -----------------------------------------------------------------------------
-- ⚠️ CETTE CONTRAINTE NE PEUT PAS ETRE UN `CHECK`.
--
--    Un CHECK ne voit qu une seule ligne : depuis `utilisateur`, il ne peut
--    pas interroger `identite_sociale`. PostgreSQL refuserait une
--    sous-requete, et une fonction contournant l interdiction mentirait des
--    qu une identite serait supprimee dans la meme transaction.
--
--    On la porte donc par un TRIGGER, arme sur les deux tables : c est le seul
--    moyen de la verifier au bon moment dans les deux sens.
--
--    C est la troisieme fois du projet qu une regle depasse ce qu une colonne
--    sait exprimer (I-06, commande_total_coherent, celle-ci).
CREATE OR REPLACE FUNCTION verifier_moyen_de_connexion() RETURNS trigger AS $$
DECLARE
    cible   bigint;
    restant int;
BEGIN
    -- ⚠️ UN `IF`, ET SURTOUT PAS UN `CASE` DANS UNE SEULE EXPRESSION.
    --
    --    La premiere version ecrivait :
    --        cible := CASE TG_TABLE_NAME
    --                     WHEN 'utilisateur' THEN NEW.id
    --                     ELSE OLD.utilisateur_id
    --                 END;
    --    et echouait au demarrage :
    --        ERREUR: l enregistrement « old » n a pas de champs « utilisateur_id »
    --
    --    PL/pgSQL prepare l expression ENTIERE comme une seule requete : les
    --    DEUX branches doivent exister pour le type de la table courante, meme
    --    celle qu on ne prendra pas. Sur `utilisateur`, OLD n a evidemment pas
    --    de colonne utilisateur_id — et l INSERT n a meme pas de OLD du tout.
    --
    --    Avec un IF, ce sont deux instructions distinctes : seule celle qui
    --    s execute est analysee.
    IF TG_TABLE_NAME = 'utilisateur' THEN
        cible := NEW.id;
    ELSE
        cible := OLD.utilisateur_id;
    END IF;

    -- Le compte vient-il d etre supprime ? Alors il n y a plus rien a verifier.
    IF NOT EXISTS (SELECT 1 FROM utilisateur WHERE id = cible) THEN
        RETURN NULL;
    END IF;

    IF EXISTS (SELECT 1 FROM utilisateur WHERE id = cible AND mot_de_passe IS NOT NULL) THEN
        RETURN NULL;
    END IF;

    SELECT count(*) INTO restant FROM identite_sociale WHERE utilisateur_id = cible;

    IF restant = 0 THEN
        RAISE EXCEPTION
            'Le compte % n aurait plus aucun moyen de connexion : ni mot de passe, ni identite sociale.',
            cible
            -- ⚠️ 23514 et non P0001 : sans ce code, Spring traduit en
            --    JpaSystemException et le client recoit 500 au lieu de 409.
            --    Lecon de la migration V19, qui avait deja corrige ce piege
            --    sur deux autres triggers.
            USING ERRCODE = '23514';
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- DEFERRABLE INITIALLY DEFERRED : la verification a lieu au COMMIT.
--
-- Indispensable. Une inscription par Google insere l utilisateur (sans mot de
-- passe) PUIS son identite : verifier immediatement refuserait la premiere
-- ligne, alors que la transaction complete est parfaitement valide.
CREATE CONSTRAINT TRIGGER utilisateur_a_un_moyen_de_connexion
    AFTER INSERT OR UPDATE OF mot_de_passe ON utilisateur
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION verifier_moyen_de_connexion();

CREATE CONSTRAINT TRIGGER identite_sociale_laisse_un_moyen_de_connexion
    AFTER DELETE ON identite_sociale
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION verifier_moyen_de_connexion();


-- -----------------------------------------------------------------------------
-- 4. Un rattachement social est un EVENEMENT DE SECURITE a part entiere
-- -----------------------------------------------------------------------------
-- Il aurait ete plus rapide de reutiliser CHANGEMENT_MOT_DE_PASSE, qui pese
-- deja dans le score de risque. Ce serait une erreur : le chapitre 18 exige un
-- score EXPLICABLE, et l ecran d administration affiche des phrases, pas des
-- nombres. « 3 changements de mot de passe » alors que la personne n a fait que
-- lier son compte Google est une phrase FAUSSE — et une decision prise dessus
-- serait arbitraire.
--
-- ⚠️ Un CHECK ne s etend pas : il se remplace. On le supprime et on le recree
--    avec la valeur en plus. Les lignes existantes restent valides, puisqu on
--    n a rien retire.
ALTER TABLE evenement_securite
    DROP CONSTRAINT evenement_securite_type_valide;

ALTER TABLE evenement_securite
    ADD CONSTRAINT evenement_securite_type_valide CHECK (type IN (
        'CONNEXION_REUSSIE', 'ECHEC_CONNEXION', 'NOUVEL_APPAREIL',
        'CHANGEMENT_MOT_DE_PASSE', 'CHANGEMENT_EMAIL', 'CHANGEMENT_TELEPHONE',
        'ECHEC_PAIEMENT', 'ACTIVITE_INHABITUELLE', 'BLOCAGE_COMPTE',
        'RATTACHEMENT_SOCIAL'));
