-- =============================================================================
-- V39 — « Continuer avec WhatsApp »
-- =============================================================================
-- ⚠️ LISEZ CECI AVANT DE TOUCHER A CE FICHIER.
--
--    WhatsApp n est PAS un fournisseur d identite. Meta n expose aucune API de
--    connexion : ni OAuth, ni jeton d identite. Ce que l API WhatsApp Business
--    sait faire, c est ENVOYER UN MESSAGE.
--
--    La mecanique reelle derriere le bouton est donc :
--
--        numero de telephone  →  code a usage unique envoye sur WhatsApp
--                             →  code verifie par NOUS
--
--    Consequence, et elle est structurante : avec Google, Google atteste
--    l identite et nous verifions une signature. Ici, GARAH EST le
--    fournisseur d identite. Toute la charge de securite — expiration,
--    plafond de tentatives, limitation de debit, resistance a l enumeration
--    des numeros — nous revient.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Un compte peut n avoir AUCUNE adresse e-mail
-- -----------------------------------------------------------------------------
-- Quelqu un qui entre par son numero n en fournit pas. Lui en fabriquer une —
-- « 237699000000@garah.me » — serait le meme piege que d inventer un mot de
-- passe en V38 : une donnee qui a l air vraie, que personne ne releve, et vers
-- laquelle on finirait par envoyer une facture.
--
-- ⚠️ L index unique sur lower(email) reste en place, et c est correct :
--    PostgreSQL autorise autant de NULL qu on veut dans un index unique.
--    Deux comptes sans adresse ne se marchent donc pas dessus.
ALTER TABLE utilisateur
    ALTER COLUMN email DROP NOT NULL;

COMMENT ON COLUMN utilisateur.email IS
    'Nullable depuis V39 : un compte ouvert par WhatsApp n''en a pas. '
    'Il en faudra une, confirmee, pour COMMANDER (D-23).';


-- -----------------------------------------------------------------------------
-- 2. WhatsApp rejoint les fournisseurs d identite
-- -----------------------------------------------------------------------------
-- ⚠️ Le `sujet` d une identite WhatsApp est le NUMERO NORMALISE au format
--    E.164 (+237699000000). C est lui qui porte l unicite, via l index
--    identite_sociale_unique (fournisseur, sujet) pose en V38.
--
--    D ou une exigence absolue cote Java : la normalisation doit etre
--    DETERMINISTE. « 699 00 00 00 », « +237699000000 » et « 00237699000000 »
--    doivent produire la meme chaine — sinon la meme personne se retrouve avec
--    trois comptes, et ses commandes eparpillees entre eux.
ALTER TABLE identite_sociale
    DROP CONSTRAINT identite_sociale_fournisseur_valide;

ALTER TABLE identite_sociale
    ADD CONSTRAINT identite_sociale_fournisseur_valide
        CHECK (fournisseur IN ('GOOGLE', 'FACEBOOK', 'TIKTOK', 'WHATSAPP'));

-- Le trigger de V38 — « un mot de passe OU une identite sociale » — couvre
-- deja ce cas sans modification : une identite WhatsApp EST une identite
-- sociale. Rien a rearmer.


-- -----------------------------------------------------------------------------
-- 3. Les codes a usage unique
-- -----------------------------------------------------------------------------
CREATE TABLE code_connexion (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Le numero normalise E.164. PAS de cle etrangere vers utilisateur :
    -- au moment ou le code part, le compte n existe peut-etre pas encore.
    telephone       varchar(20) NOT NULL,

    -- ⚠️ HACHE, jamais en clair.
    --
    --    Un code a six chiffres qui vit cinq minutes parait anodin. Mais
    --    quiconque lit cette table — une sauvegarde, une console SQL, un
    --    export — pourrait se connecter en tant que n importe qui pendant ces
    --    cinq minutes, sans jamais toucher au telephone de la victime.
    --    C est exactement le raisonnement qui interdit de stocker un mot de
    --    passe en clair, avec une fenetre plus courte.
    code_hache      varchar(255) NOT NULL,

    date_expiration timestamptz NOT NULL,

    -- Plafond des essais. Sans lui, six chiffres se devinent : un million de
    -- combinaisons se parcourent en quelques minutes avec un script.
    tentatives      int         NOT NULL DEFAULT 0,

    -- Un code servi ne resservira pas. « A usage unique » doit etre vrai.
    consomme        boolean     NOT NULL DEFAULT false,

    date_creation   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT code_connexion_tentatives_positives CHECK (tentatives >= 0)
);

-- La lecture faite a chaque verification : le dernier code vivant d un numero.
CREATE INDEX code_connexion_recherche_idx
    ON code_connexion (telephone, date_expiration DESC)
    WHERE NOT consomme;

-- ⚠️ Un seul code VIVANT par numero a la fois.
--
--    Sans cette regle, demander trois codes d affilee en laisserait trois
--    valables : on multiplie par trois les chances d en deviner un, et on
--    offre un moyen d envoyer autant de messages qu on veut au telephone de
--    quelqu un d autre. Le service invalide les precedents avant d en emettre
--    un nouveau ; cet index le GARANTIT.
CREATE UNIQUE INDEX code_connexion_un_seul_vivant
    ON code_connexion (telephone)
    WHERE NOT consomme;

-- Pour la purge : les codes expires n ont plus aucune valeur, et garder des
-- empreintes de secrets perimes n apporte rien.
CREATE INDEX code_connexion_purge_idx ON code_connexion (date_expiration);

COMMENT ON TABLE code_connexion IS
    'Codes a usage unique envoyes par WhatsApp. Haches, expirants, '
    'plafonnes en tentatives, et un seul vivant par numero.';
