-- =============================================================================
-- V3 — Marchands
-- =============================================================================
-- Le Marchand est le propriétaire économique des produits. Il N'EST PAS un
-- utilisateur du SI en v1 : il n'a pas de compte et ne se connecte pas.
-- Voir chapitre 01 §3.3.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- MARCHAND
-- -----------------------------------------------------------------------------
CREATE TABLE marchand (
    id                  bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                varchar(20)  NOT NULL UNIQUE,
    nom                 varchar(150) NOT NULL,
    type                varchar(10)  NOT NULL,
    telephone           varchar(30),
    email               varchar(255),
    statut              varchar(20)  NOT NULL DEFAULT 'ACTIF',
    date_creation       timestamptz  NOT NULL DEFAULT now(),
    date_modification   timestamptz,

    CONSTRAINT marchand_type_valide   CHECK (type IN ('INTERNE', 'EXTERNE')),
    CONSTRAINT marchand_statut_valide CHECK (statut IN ('ACTIF', 'INACTIF'))
);

COMMENT ON COLUMN marchand.type IS
    'INTERNE : l''entreprise vend ses propres produits. EXTERNE : produits d''un partenaire.';


-- -----------------------------------------------------------------------------
-- GESTION_MARCHAND — quel responsable gère la relation commerciale
-- -----------------------------------------------------------------------------
-- À ne pas confondre avec la propriété du produit (le marchand) ni avec
-- l'auteur d'une action (tracé dans audit_log). Trois notions distinctes.
-- -----------------------------------------------------------------------------
CREATE TABLE gestion_marchand (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsable_id  bigint      NOT NULL REFERENCES responsable (id),
    marchand_id     bigint      NOT NULL REFERENCES marchand (id),
    date_debut      timestamptz NOT NULL DEFAULT now(),
    date_fin        timestamptz,
    statut          varchar(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT gestion_marchand_statut_valide CHECK (statut IN ('ACTIVE', 'TERMINEE')),
    CONSTRAINT gestion_marchand_dates_coherentes
        CHECK (date_fin IS NULL OR date_fin >= date_debut)
);

-- Un marchand n'est géré que par un seul responsable à la fois.
-- Index unique partiel sur les affectations encore ouvertes.
CREATE UNIQUE INDEX gestion_marchand_active_unique
    ON gestion_marchand (marchand_id) WHERE date_fin IS NULL;

CREATE INDEX gestion_marchand_responsable_idx ON gestion_marchand (responsable_id);
