-- =============================================================================
-- V4 — Catalogue : catégories, produits, variantes, médias, prix
-- =============================================================================
-- Décision D-01 : les produits sont déclinés en VARIANTES.
--   PRODUIT   = ce que le client voit    (nom, description, photos)  → PAS de prix
--   VARIANTE  = ce qu'on vend réellement (SKU)                       → prix et stock
-- Un produit sans déclinaison a QUAND MÊME une variante, dite par défaut :
-- un seul chemin de code, toujours.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- CATEGORIE_PRODUIT — arborescente (correction A17)
-- -----------------------------------------------------------------------------
CREATE TABLE categorie_produit (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  bigint       REFERENCES categorie_produit (id),
    nom        varchar(150) NOT NULL,
    slug       varchar(150) NOT NULL UNIQUE,
    ordre      int          NOT NULL DEFAULT 0,
    statut     varchar(20)  NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT categorie_produit_statut_valide CHECK (statut IN ('ACTIVE', 'INACTIVE')),
    -- Une catégorie ne peut pas être son propre parent.
    -- (Les cycles plus longs, eux, restent à la charge du service.)
    CONSTRAINT categorie_produit_parent_different CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE INDEX categorie_produit_parent_idx ON categorie_produit (parent_id);


-- -----------------------------------------------------------------------------
-- PRODUIT
-- -----------------------------------------------------------------------------
CREATE TABLE produit (
    id                 bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marchand_id        bigint        NOT NULL REFERENCES marchand (id),
    categorie_id       bigint        NOT NULL REFERENCES categorie_produit (id),
    reference          varchar(50)   NOT NULL UNIQUE,
    nom                varchar(200)  NOT NULL,
    slug               varchar(220)  NOT NULL UNIQUE,
    description        text,
    caracteristiques   jsonb         NOT NULL DEFAULT '{}'::jsonb,
    taux_tva           numeric(5,2)  NOT NULL DEFAULT 0,
    statut             varchar(20)   NOT NULL DEFAULT 'BROUILLON',
    cree_par           bigint        REFERENCES utilisateur (id),
    modifie_par        bigint        REFERENCES utilisateur (id),
    date_creation      timestamptz   NOT NULL DEFAULT now(),
    date_modification  timestamptz,

    CONSTRAINT produit_statut_valide
        CHECK (statut IN ('BROUILLON', 'PUBLIE', 'MASQUE', 'ARCHIVE')),
    CONSTRAINT produit_taux_tva_valide
        CHECK (taux_tva >= 0 AND taux_tva < 100)
);

COMMENT ON COLUMN produit.taux_tva IS
    'Taux courant, 0 en v1 (D-11). Il est FIGÉ dans ligne_commande au moment de la vente.';
COMMENT ON COLUMN produit.caracteristiques IS
    'Attributs libres non structurants (matière, garantie…). Ce qui sert à filtrer doit devenir une vraie colonne.';

CREATE INDEX produit_marchand_idx  ON produit (marchand_id);
CREATE INDEX produit_categorie_idx ON produit (categorie_id);
CREATE INDEX produit_statut_idx    ON produit (statut) WHERE statut = 'PUBLIE';


-- -----------------------------------------------------------------------------
-- ATTRIBUT et VALEUR_ATTRIBUT — la grille de déclinaison
-- -----------------------------------------------------------------------------
CREATE TABLE attribut (
    id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             varchar(40) NOT NULL UNIQUE,
    nom              varchar(100) NOT NULL,
    type_affichage   varchar(20) NOT NULL DEFAULT 'LISTE',

    CONSTRAINT attribut_type_affichage_valide CHECK (type_affichage IN ('LISTE', 'PASTILLE'))
);

CREATE TABLE valeur_attribut (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribut_id       bigint      NOT NULL REFERENCES attribut (id) ON DELETE CASCADE,
    code              varchar(40) NOT NULL,
    libelle           varchar(100) NOT NULL,
    valeur_affichage  varchar(20),
    ordre             int         NOT NULL DEFAULT 0,

    CONSTRAINT valeur_attribut_unique UNIQUE (attribut_id, code)
);

COMMENT ON COLUMN valeur_attribut.valeur_affichage IS
    'Code couleur hexadécimal pour les attributs affichés en pastille.';


-- -----------------------------------------------------------------------------
-- VARIANTE — la référence réellement vendable
-- -----------------------------------------------------------------------------
CREATE TABLE variante (
    id           bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produit_id   bigint        NOT NULL REFERENCES produit (id) ON DELETE CASCADE,
    sku          varchar(60)   NOT NULL UNIQUE,
    libelle      varchar(200),
    poids_kg     numeric(10,3),
    par_defaut   boolean       NOT NULL DEFAULT false,
    statut       varchar(20)   NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT variante_statut_valide CHECK (statut IN ('ACTIVE', 'INACTIVE'))
);

COMMENT ON COLUMN variante.par_defaut IS
    'true pour un produit sans déclinaison réelle. Le code ne doit JAMAIS tester ce champ pour choisir un chemin.';

CREATE INDEX variante_produit_idx ON variante (produit_id);

-- Une seule variante par défaut par produit.
CREATE UNIQUE INDEX variante_par_defaut_unique
    ON variante (produit_id) WHERE par_defaut;


CREATE TABLE variante_attribut (
    variante_id         bigint NOT NULL REFERENCES variante (id) ON DELETE CASCADE,
    valeur_attribut_id  bigint NOT NULL REFERENCES valeur_attribut (id),

    PRIMARY KEY (variante_id, valeur_attribut_id)
);


-- -----------------------------------------------------------------------------
-- MEDIA — photos et vidéos
-- -----------------------------------------------------------------------------
-- On stocke une CLÉ D'OBJET, pas une URL complète (D-14).
-- Changer d'hébergeur de fichiers ne doit pas obliger à réécrire la table.
-- -----------------------------------------------------------------------------
CREATE TABLE media (
    id             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produit_id     bigint       NOT NULL REFERENCES produit (id) ON DELETE CASCADE,
    variante_id    bigint       REFERENCES variante (id) ON DELETE CASCADE,
    type           varchar(10)  NOT NULL,
    cle_objet      varchar(500) NOT NULL,
    cle_miniature  varchar(500),
    ordre          int          NOT NULL DEFAULT 0,
    principal      boolean      NOT NULL DEFAULT false,
    date_creation  timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT media_type_valide CHECK (type IN ('PHOTO', 'VIDEO'))
);

COMMENT ON COLUMN media.cle_objet IS
    'Clé dans le stockage objet, ex. produits/42/photo-1.jpg. L''URL est reconstruite à l''affichage.';

CREATE INDEX media_produit_idx ON media (produit_id);

-- I-13 : une seule photo principale par produit.
CREATE UNIQUE INDEX media_principal_unique
    ON media (produit_id) WHERE principal;


-- -----------------------------------------------------------------------------
-- TARIFICATION — le prix par palier de quantité
-- -----------------------------------------------------------------------------
-- Les prix sont stockés en TTC (D-11) : activer la TVA ne fera bondir aucun
-- prix affiché, elle sera EXTRAITE du montant.
-- -----------------------------------------------------------------------------
CREATE TABLE tarification (
    id              bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variante_id     bigint        NOT NULL REFERENCES variante (id) ON DELETE CASCADE,
    quantite_min    int           NOT NULL,
    quantite_max    int,
    prix_unitaire   numeric(15,2) NOT NULL,
    devise          char(3)       NOT NULL DEFAULT 'XAF',
    date_debut      date          NOT NULL DEFAULT CURRENT_DATE,
    date_fin        date,

    CONSTRAINT tarification_quantites_coherentes
        CHECK (quantite_min >= 1 AND (quantite_max IS NULL OR quantite_max >= quantite_min)),
    CONSTRAINT tarification_quantite_max_bornee
        CHECK (quantite_max IS NULL OR quantite_max < 1000000),
    CONSTRAINT tarification_prix_positif
        CHECK (prix_unitaire > 0),
    CONSTRAINT tarification_dates_coherentes
        CHECK (date_fin IS NULL OR date_fin >= date_debut)
);

COMMENT ON COLUMN tarification.prix_unitaire IS 'Prix TTC affiché au client (D-11).';
COMMENT ON COLUMN tarification.quantite_max IS 'NULL signifie "et au-delà".';

-- I-10 : les paliers d'une même variante ne se chevauchent JAMAIS,
-- ni en quantité, ni dans le temps.
--
-- C'est une CONTRAINTE D'EXCLUSION : elle refuse deux lignes dont les
-- intervalles se recouvrent. Elle n'existe pas en MySQL, et c'est l'une des
-- meilleures raisons de rester sur PostgreSQL.
--
-- Note : on écrit COALESCE(quantite_max + 1, ...) avec une borne haute
-- EXCLUSIVE. Utiliser '[]' avec 2147483647 déborderait la plage int4.
ALTER TABLE tarification ADD CONSTRAINT tarification_sans_chevauchement
    EXCLUDE USING gist (
        variante_id WITH =,
        int4range(quantite_min, COALESCE(quantite_max + 1, 1000000)) WITH &&,
        daterange(date_debut, date_fin) WITH &&
    );

CREATE INDEX tarification_variante_idx ON tarification (variante_id);
