-- =============================================================================
-- V5 — Stock et mouvements
-- =============================================================================
-- Le stock porte sur la VARIANTE, pas sur le produit (D-01).
--
-- Séparation stricte (correction A5) :
--   STOCK           = l'état PHYSIQUE actuel      (ça monte et ça descend)
--   MOUVEMENT_STOCK = l'historique COMPLET        (ça ne s'efface jamais)
-- Les cumuls (vendu, retourné) se DÉDUISENT des mouvements : ils ne sont pas
-- stockés dans stock, où ils inviteraient à des additions absurdes.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- STOCK
-- -----------------------------------------------------------------------------
CREATE TABLE stock (
    id                    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variante_id           bigint      NOT NULL UNIQUE REFERENCES variante (id) ON DELETE CASCADE,
    quantite_disponible   int         NOT NULL DEFAULT 0,
    quantite_reservee     int         NOT NULL DEFAULT 0,
    quantite_endommagee   int         NOT NULL DEFAULT 0,
    seuil_alerte          int         NOT NULL DEFAULT 0,
    date_modification     timestamptz NOT NULL DEFAULT now(),

    -- I-14 : l'invariant le plus important de tout le SI.
    -- Même un UPDATE écrit à la main un dimanche soir ne peut pas le violer.
    CONSTRAINT stock_quantites_positives
        CHECK (quantite_disponible >= 0
           AND quantite_reservee   >= 0
           AND quantite_endommagee >= 0)
);

COMMENT ON COLUMN stock.quantite_reservee IS
    'Engagée par une commande en attente de paiement. Indispensable car le mobile money est asynchrone (D-06).';


-- -----------------------------------------------------------------------------
-- MOUVEMENT_STOCK — l'historique, immuable
-- -----------------------------------------------------------------------------
CREATE TABLE mouvement_stock (
    id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id         bigint      NOT NULL REFERENCES stock (id),
    type             varchar(20) NOT NULL,
    quantite         int         NOT NULL,
    quantite_avant   int         NOT NULL,
    quantite_apres   int         NOT NULL,
    origine_type     varchar(20) NOT NULL,
    origine_id       bigint,
    responsable_id   bigint      REFERENCES responsable (id),
    commentaire      text,
    date_operation   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT mouvement_stock_type_valide CHECK (type IN (
        'ENTREE', 'SORTIE', 'RESERVATION', 'LIBERATION',
        'RETOUR', 'CASSE', 'AJUSTEMENT')),

    CONSTRAINT mouvement_stock_origine_valide CHECK (origine_type IN (
        'COMMANDE', 'RETOUR', 'EXPEDITION', 'INVENTAIRE', 'MANUEL')),

    -- I-16 : le mouvement doit être arithmétiquement cohérent.
    -- Sans ça, un historique peut « raconter » n'importe quoi.
    CONSTRAINT mouvement_stock_arithmetique
        CHECK (quantite_apres = quantite_avant + quantite),

    CONSTRAINT mouvement_stock_quantite_non_nulle
        CHECK (quantite <> 0)
);

COMMENT ON TABLE mouvement_stock IS
    'IMMUABLE : aucun UPDATE ni DELETE ne doit être accordé sur cette table (I-18). Une erreur se corrige par un mouvement inverse.';
COMMENT ON COLUMN mouvement_stock.origine_type IS
    'Pourquoi ce mouvement a eu lieu. Sans cette colonne, un écart de stock est indébrouillable (A5).';
COMMENT ON COLUMN mouvement_stock.responsable_id IS
    'NULL quand le mouvement est automatique (réservation à la commande, libération par expiration).';

CREATE INDEX mouvement_stock_stock_date_idx ON mouvement_stock (stock_id, date_operation DESC);
CREATE INDEX mouvement_stock_origine_idx    ON mouvement_stock (origine_type, origine_id);
