-- =============================================================================
-- V6 — Lieux et itinéraires
-- =============================================================================
-- Correction A10 : une table LIEU unique remplace point_transit et
-- point_recuperation. Sinon on ne peut pas enregistrer le départ de l'entrepôt
-- ni la remise au client — les deux événements les plus importants du parcours.
--
-- Cette migration vient AVANT le commerce, parce qu'une commande référence son
-- point de récupération, choisi au moment de l'achat (D-05).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- LIEU
-- -----------------------------------------------------------------------------
CREATE TABLE lieu (
    id                   bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                 varchar(20)   NOT NULL,
    nom                  varchar(150)  NOT NULL,
    pays                 varchar(80)   NOT NULL,
    ville                varchar(100)  NOT NULL,
    adresse              text,
    telephone            varchar(30),
    horaires             varchar(200),
    frais_acheminement   numeric(15,2) NOT NULL DEFAULT 0,
    latitude             numeric(10,7),
    longitude            numeric(10,7),
    statut               varchar(20)   NOT NULL DEFAULT 'ACTIF',

    CONSTRAINT lieu_type_valide
        CHECK (type IN ('ENTREPOT', 'POINT_TRANSIT', 'POINT_RECUPERATION')),
    CONSTRAINT lieu_statut_valide
        CHECK (statut IN ('ACTIF', 'INACTIF')),
    CONSTRAINT lieu_frais_positifs
        CHECK (frais_acheminement >= 0),

    -- Astuce : cette contrainte d'unicité redondante (id est déjà PK) permet
    -- à d'autres tables de poser une clé étrangère COMPOSITE (id, type) et
    -- donc de garantir en base qu'un point de récupération en est bien un.
    -- Voir commande.point_recuperation_id en V7. C'est une dénormalisation
    -- assumée : elle transforme un trigger en simple clé étrangère (I-25).
    CONSTRAINT lieu_id_type_unique UNIQUE (id, type)
);

COMMENT ON COLUMN lieu.frais_acheminement IS
    'Facturé au client, copié dans commande.montant_frais (D-10). Ne dépend PAS du poids : les marchands l''ignorent (D-13).';

CREATE INDEX lieu_type_statut_idx ON lieu (type, statut);
CREATE INDEX lieu_ville_idx       ON lieu (ville);


-- -----------------------------------------------------------------------------
-- ITINERAIRE — un MODÈLE de trajet, réutilisable
-- -----------------------------------------------------------------------------
-- À ne pas confondre avec le trajet RÉEL du colis, qui vit dans les
-- événements d'expédition (V9) et peut s'écarter du modèle.
-- -----------------------------------------------------------------------------
CREATE TABLE itineraire (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom               varchar(150) NOT NULL,
    lieu_depart_id    bigint       NOT NULL REFERENCES lieu (id),
    lieu_arrivee_id   bigint       NOT NULL REFERENCES lieu (id),
    statut            varchar(20)  NOT NULL DEFAULT 'ACTIF',

    CONSTRAINT itineraire_statut_valide CHECK (statut IN ('ACTIF', 'INACTIF')),
    CONSTRAINT itineraire_extremites_differentes CHECK (lieu_depart_id <> lieu_arrivee_id)
);


CREATE TABLE etape_itineraire (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itineraire_id          bigint NOT NULL REFERENCES itineraire (id) ON DELETE CASCADE,
    lieu_id                bigint NOT NULL REFERENCES lieu (id),
    ordre                  int    NOT NULL,
    duree_estimee_heures   int,

    -- I-34 : deux étapes ne peuvent pas occuper le même rang.
    CONSTRAINT etape_itineraire_ordre_unique UNIQUE (itineraire_id, ordre),
    CONSTRAINT etape_itineraire_ordre_positif CHECK (ordre >= 1),
    CONSTRAINT etape_itineraire_duree_positive
        CHECK (duree_estimee_heures IS NULL OR duree_estimee_heures > 0)
);

CREATE INDEX etape_itineraire_lieu_idx ON etape_itineraire (lieu_id);
