-- =============================================================================
-- V7 — Commerce : panier, commande, paiement
-- =============================================================================
-- C'est ici que vit la RÈGLE DE LA PHOTOGRAPHIE (règle fondatrice n°4) :
-- tout ce qui a une valeur juridique ou financière au moment de la vente est
-- COPIÉ dans la transaction, jamais seulement référencé.
-- Une référence pointe vers une donnée qui changera. Une copie est un fait.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- PANIER — historisé, un seul actif à la fois (correction A8)
-- -----------------------------------------------------------------------------
CREATE TABLE panier (
    id                 bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id          bigint      NOT NULL REFERENCES client (id) ON DELETE CASCADE,
    statut             varchar(20) NOT NULL DEFAULT 'ACTIF',
    date_creation      timestamptz NOT NULL DEFAULT now(),
    date_modification  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT panier_statut_valide CHECK (statut IN ('ACTIF', 'CONVERTI', 'ABANDONNE'))
);

-- I-19 : un seul panier ACTIF par client. Les paniers abandonnés sont conservés,
-- car la statistique « paniers abandonnés » de la §20 en dépend.
CREATE UNIQUE INDEX panier_actif_unique
    ON panier (client_id) WHERE statut = 'ACTIF';


CREATE TABLE ligne_panier (
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panier_id    bigint      NOT NULL REFERENCES panier (id) ON DELETE CASCADE,
    variante_id  bigint      NOT NULL REFERENCES variante (id),
    quantite     int         NOT NULL,
    date_ajout   timestamptz NOT NULL DEFAULT now(),

    -- I-20 : une variante n'apparaît qu'une fois par panier (on incrémente).
    CONSTRAINT ligne_panier_unique UNIQUE (panier_id, variante_id),
    CONSTRAINT ligne_panier_quantite_positive CHECK (quantite > 0)
);


-- -----------------------------------------------------------------------------
-- COMMANDE
-- -----------------------------------------------------------------------------
CREATE TABLE commande (
    id                        bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero                    varchar(30)   NOT NULL UNIQUE,
    client_id                 bigint        NOT NULL REFERENCES client (id),
    conversation_id           bigint,   -- clé étrangère ajoutée en V8 (dépendance circulaire)
    point_recuperation_id     bigint        NOT NULL,
    point_recuperation_type   varchar(20)   NOT NULL DEFAULT 'POINT_RECUPERATION',
    langue                    char(2)       NOT NULL DEFAULT 'fr' REFERENCES langue (code),
    statut                    varchar(30)   NOT NULL DEFAULT 'EN_ATTENTE_PAIEMENT',
    montant_articles          numeric(15,2) NOT NULL DEFAULT 0,
    montant_frais             numeric(15,2) NOT NULL DEFAULT 0,
    montant_remise            numeric(15,2) NOT NULL DEFAULT 0,
    montant_total             numeric(15,2) NOT NULL DEFAULT 0,
    montant_tva               numeric(15,2) NOT NULL DEFAULT 0,
    devise                    char(3)       NOT NULL DEFAULT 'XAF',
    date_creation             timestamptz   NOT NULL DEFAULT now(),
    date_modification         timestamptz,

    CONSTRAINT commande_statut_valide CHECK (statut IN (
        'EN_ATTENTE_PAIEMENT', 'PAYEE', 'EN_PREPARATION', 'PRETE',
        'EXPEDIEE', 'DISPONIBLE', 'RETIREE', 'ANNULEE')),

    -- I-21 : le total ne peut PAS être faux. C'est la contrainte qui protège
    -- le plus d'argent pour le moins d'effort.
    CONSTRAINT commande_total_coherent
        CHECK (montant_total = montant_articles + montant_frais - montant_remise),

    CONSTRAINT commande_montants_positifs
        CHECK (montant_articles >= 0 AND montant_frais >= 0
           AND montant_remise   >= 0 AND montant_total >= 0),

    -- I-25 : le lieu choisi est FORCÉMENT un point de récupération.
    -- La colonne point_recuperation_type est figée par le CHECK ci-dessous ;
    -- la clé étrangère COMPOSITE fait le reste. Un trigger devient inutile.
    CONSTRAINT commande_point_recuperation_type_fige
        CHECK (point_recuperation_type = 'POINT_RECUPERATION'),
    CONSTRAINT commande_point_recuperation_fk
        FOREIGN KEY (point_recuperation_id, point_recuperation_type)
        REFERENCES lieu (id, type)
);

COMMENT ON COLUMN commande.point_recuperation_id IS
    'Choisi à la commande parmi les points actifs (D-05). Il n''existe pas de préférence sur le profil client.';
COMMENT ON COLUMN commande.langue IS
    'PHOTO : la langue d''émission du document. Une facture émise en sango le reste (D-09).';
COMMENT ON COLUMN commande.montant_tva IS
    'Somme des TVA de lignes, informatif. Vaut 0 tant que les taux valent 0 (D-11).';

CREATE INDEX commande_client_idx      ON commande (client_id, date_creation DESC);
CREATE INDEX commande_statut_idx      ON commande (statut);
CREATE INDEX commande_point_recup_idx ON commande (point_recuperation_id);


-- -----------------------------------------------------------------------------
-- LIGNE_COMMANDE — cinq colonnes sont des PHOTOS, et c'est volontaire
-- -----------------------------------------------------------------------------
CREATE TABLE ligne_commande (
    id                    bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id           bigint        NOT NULL REFERENCES commande (id) ON DELETE CASCADE,
    variante_id           bigint        NOT NULL REFERENCES variante (id),
    marchand_id           bigint        NOT NULL REFERENCES marchand (id),
    proposition_prix_id   bigint,   -- clé étrangère ajoutée en V8
    designation           varchar(250)  NOT NULL,
    attributs             jsonb         NOT NULL DEFAULT '{}'::jsonb,
    quantite              int           NOT NULL,
    prix_unitaire         numeric(15,2) NOT NULL,
    montant_ligne         numeric(15,2) NOT NULL,
    taux_tva              numeric(5,2)  NOT NULL DEFAULT 0,
    montant_tva           numeric(15,2) NOT NULL DEFAULT 0,
    taux_commission       numeric(5,2)  NOT NULL DEFAULT 0,
    montant_commission    numeric(15,2) NOT NULL DEFAULT 0,

    CONSTRAINT ligne_commande_quantite_positive CHECK (quantite > 0),
    CONSTRAINT ligne_commande_prix_positif      CHECK (prix_unitaire > 0),

    -- I-22
    CONSTRAINT ligne_commande_montant_coherent
        CHECK (montant_ligne = quantite * prix_unitaire),

    -- I-23 : la commission est arithmétiquement vérifiable.
    CONSTRAINT ligne_commande_commission_coherente
        CHECK (montant_commission = round(montant_ligne * taux_commission / 100, 2)),

    -- D-11 : la TVA est EXTRAITE d'un prix TTC, pas ajoutée à un prix HT.
    --        montant_tva = TTC × taux / (100 + taux)
    CONSTRAINT ligne_commande_tva_coherente
        CHECK (montant_tva = round(montant_ligne * taux_tva / (100 + taux_tva), 2)),

    CONSTRAINT ligne_commande_taux_valides
        CHECK (taux_tva >= 0 AND taux_tva < 100
           AND taux_commission >= 0 AND taux_commission <= 100)
);

COMMENT ON COLUMN ligne_commande.marchand_id IS
    'PHOTO. Le produit peut changer de marchand (PRODUIT_MODIFIER_MARCHAND) : on doit à ABC ce qu''ABC a vendu ce jour-là (A13).';
COMMENT ON COLUMN ligne_commande.designation IS
    'PHOTO du nom du produit au moment de la vente. Le produit peut être renommé ensuite.';
COMMENT ON COLUMN ligne_commande.proposition_prix_id IS
    'Justifie un prix inférieur au tarif. Sans elle, un écart de prix n''est pas contrôlable (A6).';

CREATE INDEX ligne_commande_commande_idx ON ligne_commande (commande_id);
CREATE INDEX ligne_commande_variante_idx ON ligne_commande (variante_id);
CREATE INDEX ligne_commande_marchand_idx ON ligne_commande (marchand_id);


-- -----------------------------------------------------------------------------
-- PAIEMENT — mobile money et virement, pas d'espèces (D-06)
-- -----------------------------------------------------------------------------
CREATE TABLE paiement (
    id                     bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id            bigint        NOT NULL REFERENCES commande (id),
    type                   varchar(20)   NOT NULL,
    montant                numeric(15,2) NOT NULL,
    devise                 char(3)       NOT NULL DEFAULT 'XAF',
    moyen                  varchar(20)   NOT NULL,
    reference_transaction  varchar(100),
    statut                 varchar(20)   NOT NULL DEFAULT 'INITIE',
    origine_type           varchar(20),
    origine_id             bigint,
    date_initiation        timestamptz   NOT NULL DEFAULT now(),
    date_confirmation      timestamptz,

    CONSTRAINT paiement_type_valide   CHECK (type  IN ('ENCAISSEMENT', 'REMBOURSEMENT')),
    CONSTRAINT paiement_moyen_valide  CHECK (moyen IN ('MTN_MOMO', 'ORANGE_MONEY', 'VIREMENT')),
    CONSTRAINT paiement_statut_valide CHECK (statut IN (
        'INITIE', 'EN_ATTENTE', 'CONFIRME', 'ECHOUE', 'ANNULE')),
    CONSTRAINT paiement_montant_positif CHECK (montant > 0),
    CONSTRAINT paiement_origine_valide
        CHECK (origine_type IS NULL OR origine_type IN ('RETOUR', 'RECLAMATION')),
    -- Un remboursement doit toujours dire ce qui le justifie.
    CONSTRAINT paiement_remboursement_justifie
        CHECK (type <> 'REMBOURSEMENT' OR origine_type IS NOT NULL),
    CONSTRAINT paiement_confirmation_coherente
        CHECK (statut <> 'CONFIRME' OR date_confirmation IS NOT NULL)
);

COMMENT ON COLUMN paiement.montant IS
    'Toujours POSITIF. Le sens est porté par la colonne type, jamais par un montant négatif (A12).';
COMMENT ON COLUMN paiement.reference_transaction IS
    'Identifiant chez l''opérateur. Sans lui, aucun litige mobile money n''est arbitrable.';

CREATE INDEX paiement_commande_idx  ON paiement (commande_id);
CREATE INDEX paiement_reference_idx ON paiement (reference_transaction);
CREATE INDEX paiement_statut_idx    ON paiement (statut, date_initiation);


-- -----------------------------------------------------------------------------
-- TENTATIVE_PAIEMENT — les échecs, qui alimentent le score de risque (§18)
-- -----------------------------------------------------------------------------
CREATE TABLE tentative_paiement (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paiement_id     bigint      NOT NULL REFERENCES paiement (id) ON DELETE CASCADE,
    statut          varchar(20) NOT NULL,
    code_erreur     varchar(50),
    message         text,
    date_tentative  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE tentative_paiement IS
    'Si on n''enregistre que les paiements réussis, le signal « échecs de paiement » du score de risque n''existe pas.';

CREATE INDEX tentative_paiement_paiement_idx ON tentative_paiement (paiement_id);
