-- =============================================================================
-- V8 — Service client : conversations, messages, négociation
-- =============================================================================
-- Cette migration ferme aussi deux dépendances CIRCULAIRES laissées ouvertes
-- en V7 :
--     commande.conversation_id        → conversation
--     ligne_commande.proposition_prix_id → proposition_prix
--
-- C'est la façon normale de traiter un cycle entre domaines : on crée la
-- colonne sans contrainte, puis on ajoute la clé étrangère quand la table
-- cible existe. Jamais l'inverse — une colonne oubliée ne se voit pas,
-- une clé étrangère manquante non plus.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- CONVERSATION
-- -----------------------------------------------------------------------------
CREATE TABLE conversation (
    id                 bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id          bigint       NOT NULL REFERENCES client (id),
    responsable_id     bigint       REFERENCES responsable (id),
    sujet              varchar(200),
    statut             varchar(20)  NOT NULL DEFAULT 'WAITING',
    date_creation      timestamptz  NOT NULL DEFAULT now(),
    date_affectation   timestamptz,
    date_cloture       timestamptz,

    CONSTRAINT conversation_statut_valide
        CHECK (statut IN ('WAITING', 'ASSIGNED', 'CLOSED')),

    -- I-29 : WAITING ⇔ pas de responsable. ASSIGNED ⇔ un responsable.
    -- Cette contrainte rend impossible l'incohérence la plus banale du
    -- module : une conversation « prise » par personne.
    CONSTRAINT conversation_responsable_coherent CHECK (
        (statut = 'WAITING'  AND responsable_id IS NULL)
     OR (statut IN ('ASSIGNED', 'CLOSED') AND responsable_id IS NOT NULL)
    )
);

CREATE INDEX conversation_client_idx  ON conversation (client_id, date_creation DESC);
CREATE INDEX conversation_attente_idx ON conversation (date_creation) WHERE statut = 'WAITING';
CREATE INDEX conversation_resp_idx    ON conversation (responsable_id) WHERE statut = 'ASSIGNED';


-- -----------------------------------------------------------------------------
-- AFFECTATION_CONVERSATION — l'historique des prises et des retraits
-- -----------------------------------------------------------------------------
-- L'Admin peut retirer une conversation à un responsable pour la donner à un
-- autre (§4 de la spec). Cette table garde la trace de qui l'a eue et quand.
-- -----------------------------------------------------------------------------
CREATE TABLE affectation_conversation (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id   bigint      NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    responsable_id    bigint      NOT NULL REFERENCES responsable (id),
    affecte_par       bigint      REFERENCES utilisateur (id),
    motif             text,
    date_debut        timestamptz NOT NULL DEFAULT now(),
    date_fin          timestamptz,

    CONSTRAINT affectation_conversation_dates_coherentes
        CHECK (date_fin IS NULL OR date_fin >= date_debut)
);

COMMENT ON COLUMN affectation_conversation.affecte_par IS
    'NULL si le responsable a pris la conversation lui-même. Renseigné en cas de réaffectation par un Admin.';

-- I-30 : une seule affectation ouverte par conversation.
CREATE UNIQUE INDEX affectation_conversation_ouverte_unique
    ON affectation_conversation (conversation_id) WHERE date_fin IS NULL;


-- -----------------------------------------------------------------------------
-- MESSAGE
-- -----------------------------------------------------------------------------
CREATE TABLE message (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id   bigint      NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    expediteur_id     bigint      NOT NULL REFERENCES utilisateur (id),
    contenu           text        NOT NULL,
    lu                boolean     NOT NULL DEFAULT false,
    date_envoi        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT message_contenu_non_vide CHECK (length(trim(contenu)) > 0)
);

CREATE INDEX message_conversation_idx ON message (conversation_id, date_envoi);


-- -----------------------------------------------------------------------------
-- PROPOSITION_PRIX — la négociation (correction A6)
-- -----------------------------------------------------------------------------
-- Le modèle initial ne disait ni sur QUOI portait la proposition, ni pour
-- quelle QUANTITÉ, ni QUI proposait, ni jusqu'à QUAND elle valait.
-- -----------------------------------------------------------------------------
CREATE TABLE proposition_prix (
    id                       bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id          bigint        NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    variante_id              bigint        NOT NULL REFERENCES variante (id),
    proposition_parente_id   bigint        REFERENCES proposition_prix (id),
    quantite                 int           NOT NULL,
    prix_unitaire_propose    numeric(15,2) NOT NULL,
    auteur_id                bigint        NOT NULL REFERENCES utilisateur (id),
    sens                     varchar(20)   NOT NULL,
    statut                   varchar(20)   NOT NULL DEFAULT 'PROPOSEE',
    date_creation            timestamptz   NOT NULL DEFAULT now(),
    date_expiration          timestamptz   NOT NULL,

    CONSTRAINT proposition_prix_sens_valide   CHECK (sens IN ('CLIENT', 'RESPONSABLE')),
    CONSTRAINT proposition_prix_statut_valide CHECK (statut IN (
        'PROPOSEE', 'ACCEPTEE', 'REFUSEE', 'EXPIREE', 'CONSOMMEE')),
    CONSTRAINT proposition_prix_quantite_positive CHECK (quantite > 0),
    CONSTRAINT proposition_prix_montant_positif   CHECK (prix_unitaire_propose > 0),
    CONSTRAINT proposition_prix_expiration_posterieure
        CHECK (date_expiration > date_creation),
    CONSTRAINT proposition_prix_parente_differente
        CHECK (proposition_parente_id IS NULL OR proposition_parente_id <> id)
);

COMMENT ON COLUMN proposition_prix.date_expiration IS
    'Obligatoire. Sans elle, un client accepte en octobre un prix proposé en mars (I-33).';

CREATE INDEX proposition_prix_conversation_idx ON proposition_prix (conversation_id);
CREATE INDEX proposition_prix_variante_idx     ON proposition_prix (variante_id);
CREATE INDEX proposition_prix_a_expirer_idx
    ON proposition_prix (date_expiration) WHERE statut = 'PROPOSEE';


-- -----------------------------------------------------------------------------
-- EVALUATION_CONVERSATION
-- -----------------------------------------------------------------------------
CREATE TABLE evaluation_conversation (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id   bigint      NOT NULL UNIQUE REFERENCES conversation (id) ON DELETE CASCADE,
    note              int         NOT NULL,
    commentaire       text,
    date_evaluation   timestamptz NOT NULL DEFAULT now(),

    -- I-32
    CONSTRAINT evaluation_conversation_note_valide CHECK (note BETWEEN 1 AND 5)
);


-- =============================================================================
-- Fermeture des dépendances circulaires laissées ouvertes en V7
-- =============================================================================
ALTER TABLE commande
    ADD CONSTRAINT commande_conversation_fk
    FOREIGN KEY (conversation_id) REFERENCES conversation (id);

CREATE INDEX commande_conversation_idx ON commande (conversation_id);

ALTER TABLE ligne_commande
    ADD CONSTRAINT ligne_commande_proposition_fk
    FOREIGN KEY (proposition_prix_id) REFERENCES proposition_prix (id);

CREATE INDEX ligne_commande_proposition_idx ON ligne_commande (proposition_prix_id);
