-- =============================================================================
-- V9 — Logistique : expéditions, colis, événements, incidents, retraits
-- =============================================================================
-- Principe directeur (règle fondatrice n°1) :
--     la VÉRITÉ est la suite des ÉVÉNEMENTS.
--     Le STATUT n'est qu'une PROJECTION du dernier événement, mise à jour dans
--     la même transaction, et RECALCULABLE à tout moment.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- EXPEDITION
-- -----------------------------------------------------------------------------
-- Une commande peut donner PLUSIEURS expéditions : marchandises de marchands
-- différents, ou plusieurs colis partant à des dates différentes.
-- L'itinéraire est FACULTATIF : une livraison locale n'en a pas (A9).
-- -----------------------------------------------------------------------------
CREATE TABLE expedition (
    id                        bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero                    varchar(30) NOT NULL UNIQUE,
    commande_id               bigint      NOT NULL REFERENCES commande (id),
    marchand_id               bigint      REFERENCES marchand (id),
    itineraire_id             bigint      REFERENCES itineraire (id),
    lieu_depart_id            bigint      NOT NULL REFERENCES lieu (id),
    point_recuperation_id     bigint      NOT NULL,
    point_recuperation_type   varchar(20) NOT NULL DEFAULT 'POINT_RECUPERATION',
    statut                    varchar(20) NOT NULL DEFAULT 'CREEE',
    date_creation             timestamptz NOT NULL DEFAULT now(),
    date_expedition           timestamptz,
    date_arrivee_prevue       timestamptz,

    CONSTRAINT expedition_statut_valide CHECK (statut IN (
        'CREEE', 'PREPAREE', 'EN_TRANSIT', 'BLOQUEE', 'DISPONIBLE', 'REMISE', 'ANNULEE')),

    CONSTRAINT expedition_point_recuperation_type_fige
        CHECK (point_recuperation_type = 'POINT_RECUPERATION'),
    CONSTRAINT expedition_point_recuperation_fk
        FOREIGN KEY (point_recuperation_id, point_recuperation_type)
        REFERENCES lieu (id, type)
);

COMMENT ON COLUMN expedition.statut IS
    'PROJECTION du dernier événement des colis. Existe pour l''affichage, jamais comme source de vérité (A11).';
COMMENT ON COLUMN expedition.itineraire_id IS
    'Le MODÈLE de trajet prévu. Le trajet réel vit dans evenement_expedition et peut s''en écarter.';

CREATE INDEX expedition_commande_idx ON expedition (commande_id);
CREATE INDEX expedition_statut_idx   ON expedition (statut);


-- -----------------------------------------------------------------------------
-- COLIS
-- -----------------------------------------------------------------------------
CREATE TABLE colis (
    id              bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expedition_id   bigint        NOT NULL REFERENCES expedition (id) ON DELETE CASCADE,
    numero_suivi    varchar(40)   NOT NULL UNIQUE,
    poids_kg        numeric(10,3),
    dimensions      varchar(50),
    statut          varchar(20)   NOT NULL DEFAULT 'CREE',

    CONSTRAINT colis_statut_valide CHECK (statut IN (
        'CREE', 'EN_TRANSIT', 'BLOQUE', 'DISPONIBLE', 'REMIS', 'PERDU'))
);

CREATE INDEX colis_expedition_idx ON colis (expedition_id);


-- -----------------------------------------------------------------------------
-- LIGNE_COLIS — ce qu'il y a RÉELLEMENT dans le colis (correction A13)
-- -----------------------------------------------------------------------------
-- Sans cette table, la question « quels articles sont dans le colis n°3 ? »
-- n'a tout simplement pas de réponse.
-- -----------------------------------------------------------------------------
CREATE TABLE ligne_colis (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colis_id            bigint NOT NULL REFERENCES colis (id) ON DELETE CASCADE,
    ligne_commande_id   bigint NOT NULL REFERENCES ligne_commande (id),
    quantite            int    NOT NULL,

    CONSTRAINT ligne_colis_quantite_positive CHECK (quantite > 0),
    CONSTRAINT ligne_colis_unique UNIQUE (colis_id, ligne_commande_id)
);

CREATE INDEX ligne_colis_ligne_commande_idx ON ligne_colis (ligne_commande_id);


-- -----------------------------------------------------------------------------
-- I-35 — On ne peut pas expédier plus que ce qui a été commandé
-- -----------------------------------------------------------------------------
-- SQL ne sait PAS exprimer « la somme des lignes filles ne dépasse pas une
-- valeur de la ligne mère » : un CHECK ne voit qu'une ligne à la fois.
-- D'où ce TRIGGER — réservé aux cas où l'erreur coûte de la marchandise réelle.
--
-- ⚠️ Un trigger est INVISIBLE depuis le code Java. Il doit donc toujours être
--    documenté ici ET dans le chapitre 04. Un trigger non documenté est un
--    piège qu'on se tend à soi-même.
-- -----------------------------------------------------------------------------
CREATE FUNCTION verifier_quantite_colis() RETURNS trigger AS $$
DECLARE
    qte_commandee int;
    qte_deja      int;
BEGIN
    SELECT quantite INTO qte_commandee
      FROM ligne_commande WHERE id = NEW.ligne_commande_id;

    SELECT COALESCE(SUM(quantite), 0) INTO qte_deja
      FROM ligne_colis
     WHERE ligne_commande_id = NEW.ligne_commande_id
       AND id IS DISTINCT FROM NEW.id;

    IF qte_deja + NEW.quantite > qte_commandee THEN
        RAISE EXCEPTION
            'I-35 : quantite en colis (%) superieure a la quantite commandee (%) pour la ligne_commande %',
            qte_deja + NEW.quantite, qte_commandee, NEW.ligne_commande_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ligne_colis_quantite_trigger
    BEFORE INSERT OR UPDATE ON ligne_colis
    FOR EACH ROW EXECUTE FUNCTION verifier_quantite_colis();


-- -----------------------------------------------------------------------------
-- EVENEMENT_EXPEDITION — la vérité du parcours, immuable
-- -----------------------------------------------------------------------------
-- Le lieu N'EST PAS contraint à appartenir à l'itinéraire prévu : une route
-- coupée, un déroutement, ça arrive. Une contrainte qui empêche d'enregistrer
-- la réalité est une mauvaise contrainte — l'opérateur saisirait n'importe
-- quoi d'autre pour continuer son travail, et la traçabilité serait perdue.
-- -----------------------------------------------------------------------------
CREATE TABLE evenement_expedition (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colis_id        bigint      NOT NULL REFERENCES colis (id),
    lieu_id         bigint      NOT NULL REFERENCES lieu (id),
    responsable_id  bigint      REFERENCES responsable (id),
    type            varchar(20) NOT NULL,
    observation     text,
    date_heure      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT evenement_expedition_type_valide CHECK (type IN (
        'DEPART', 'ARRIVEE', 'RECEPTION', 'CONTROLE', 'ANOMALIE', 'REMISE'))
);

COMMENT ON TABLE evenement_expedition IS
    'IMMUABLE (I-37) : aucun UPDATE ni DELETE. Une erreur se corrige par un événement de plus.';
COMMENT ON COLUMN evenement_expedition.date_heure IS
    'I-36 (pas de date future) est vérifié par le SERVICE : un CHECK ne peut pas appeler now(), qui n''est pas IMMUTABLE.';

CREATE INDEX evenement_expedition_colis_idx ON evenement_expedition (colis_id, date_heure DESC);
CREATE INDEX evenement_expedition_lieu_idx  ON evenement_expedition (lieu_id, date_heure DESC);


-- -----------------------------------------------------------------------------
-- INCIDENT_EXPEDITION
-- -----------------------------------------------------------------------------
CREATE TABLE incident_expedition (
    id                     bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expedition_id          bigint      NOT NULL REFERENCES expedition (id),
    colis_id               bigint      REFERENCES colis (id),
    type                   varchar(20) NOT NULL,
    gravite                varchar(20) NOT NULL,
    statut                 varchar(20) NOT NULL DEFAULT 'OUVERT',
    description            text        NOT NULL,
    declare_par            bigint      REFERENCES utilisateur (id),
    pris_en_charge_par     bigint      REFERENCES utilisateur (id),
    date_declaration       timestamptz NOT NULL DEFAULT now(),
    date_resolution        timestamptz,

    CONSTRAINT incident_type_valide    CHECK (type IN ('PERTE', 'CASSE', 'RETARD', 'VOL', 'DOUANE', 'AUTRE')),
    CONSTRAINT incident_gravite_valide CHECK (gravite IN ('FAIBLE', 'MOYENNE', 'HAUTE', 'CRITIQUE')),
    CONSTRAINT incident_statut_valide  CHECK (statut IN ('OUVERT', 'EN_COURS', 'RESOLU', 'CLASSE')),
    CONSTRAINT incident_resolution_coherente
        CHECK (statut NOT IN ('RESOLU', 'CLASSE') OR date_resolution IS NOT NULL)
);

COMMENT ON COLUMN incident_expedition.colis_id IS 'NULL quand l''incident concerne toute l''expédition.';

CREATE INDEX incident_expedition_idx        ON incident_expedition (expedition_id);
CREATE INDEX incident_expedition_ouvert_idx ON incident_expedition (gravite) WHERE statut IN ('OUVERT', 'EN_COURS');


-- -----------------------------------------------------------------------------
-- RETRAIT_MARCHANDISE — la fin du parcours
-- -----------------------------------------------------------------------------
CREATE TABLE retrait_marchandise (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expedition_id   bigint      NOT NULL UNIQUE REFERENCES expedition (id),
    client_id       bigint      NOT NULL REFERENCES client (id),
    code_retrait    varchar(20) NOT NULL UNIQUE,
    statut          varchar(20) NOT NULL DEFAULT 'EN_ATTENTE',
    confirme_par    bigint      REFERENCES responsable (id),
    date_retrait    timestamptz,

    CONSTRAINT retrait_statut_valide CHECK (statut IN ('EN_ATTENTE', 'CONFIRME', 'REFUSE')),
    CONSTRAINT retrait_confirmation_coherente
        CHECK (statut <> 'CONFIRME' OR (confirme_par IS NOT NULL AND date_retrait IS NOT NULL))
);

COMMENT ON COLUMN retrait_marchandise.code_retrait IS
    'Code présenté par le client au point de récupération. Unique, et le seul moyen de prouver la remise.';
